### ISSUE TITLE
About flakes

### ISSUE THREAD

**Issue by JakoDel** [kuruczgy/x1e-nixos-config#1] opened 2024-08-31 22:14 UTC
Thanks a ton for this basically 5 clicks install!

I am almost completely unfamiliar with flakes and what they do compared to configuration.nix even after giving the wiki a quick read, so yeah I'm not sure on what to do now to get your average install with gnome,networkmanager,pipewire etc.

I tried to generate a configuration.nix but nixos-rebuild switch says that the $NIX_PATH var is set to nixpkgs=flake:nixpkgs and I'm not sure if I can just change it to the config file path.

I'm trying to do some research on flakes, but I assumed I'd find a flake.nix inside /etc/nixos for all the slim 7x specific stuff and yet there isn't... so I'm even more confused lol. Could you give me some pointers?

Thank you.

edit: and welp, I guess I couldve also changed the source dvd from minimal to gnome before building the iso.

**Comment by kuruczgy** [comment] 2024-09-01 08:07
Hi, I am glad this repo helped someone :)

# How to use flakes

If you want to get the flake-based config working, just clone this repo onto your machine, make your edits, and run `sudo nixos-rebuild switch --flake .`

# How to use regular `configuration.nix`

If you want to get `configuration.nix` working, you will probably have to enable channels, which I disabled here: https://github.com/kuruczgy/x1e-nixos-config/blob/09fd24afeab6dd380a1040c8c465c18c56b5a196/modules/common.nix#L5 I admit that the repo is currently quite opinionated towards the way I use NixOS, but if you can submit a PR re-enabling channels and adding instructions to the README describing how to set up a regular channel + `configuration.nix` based system I would probably take it.

# Explanation of why I use flakes

Now onto explaining flakes. In the Nix world you basically have two ways of using a NixOS configuration. The original channel + `configuration.nix` method is something I would consider outdated. The issue is that channels are impure inputs to your configuration. If you want to copy your configuration to another machine, that other machine will have different versions of the channels, and so you will get different versions of packages, and in an unlucky scenario your configuration could even fail to evaluate e.g. if you are using an unstable channel. You also have no record of the previous versions of the channels on the same machine, so e.g. if something goes wrong after a channel update it's not easy to roll back to the exact previous version.

Flakes are still considered "experimental", but given that a large part of the Nix community uses them, they are _de facto_ stable enough for regular use and no one would dare (hope) making breaking changes to the flake system because so many people depend on it.

An important feature of flakes is its concept of "inputs", which can basically replace channels. Inputs are pinned in the `flake.lock` file: https://github.com/kuruczgy/x1e-nixos-config/blob/09fd24afeab6dd380a1040c8c465c18c56b5a196/flake.lock

Now, if you put your flake based config and `flake.lock` into a git repo (doesn't really make sense to use flakes without one), you have:
1. A perfectly reproducible config anyone in the world can reproduce. This is the reason I can upload this repo and be confident that it will just work for other people, without version drift or any other breakage.
2. A history of each previously used version of each input. Now if a nixpkgs update breaks something, rolling back is trivial.

Flakes do have other features too, e.g. being able to use other flakes as inputs, but I would recommend mostly just sticking to using flakes as a replacement for channels, and not much else. If you are interested in the design limitations of flakes and why you should be careful with fully embracing all of the other features, I would recommend this article: https://jade.fyi/blog/flakes-arent-real/

They way I use flakes is that I have a single flake-based NixOS config repository shared by all of my machines. (The `sudo nixos-rebuild switch --flake .` command automatically selects the right configuration based on the hostname.) This is very useful because I can share NixOS modules between them, and it's also very easy to enforce some common rules.

Hope this helped, if you have any questions feel free to ask.

**Comment by JakoDel** [comment] 2024-09-03 00:59
> Hi, I am glad this repo helped someone :)
> 
> # How to use flakes
> If you want to get the flake-based config working, just clone this repo onto your machine, make your edits, and run `sudo nixos-rebuild switch --flake .`
> 
> # How to use regular `configuration.nix`
> If you want to get `configuration.nix` working, you will probably have to enable channels, which I disabled here:
> 
> https://github.com/kuruczgy/x1e-nixos-config/blob/09fd24afeab6dd380a1040c8c465c18c56b5a196/modules/common.nix#L5
> 
> I admit that the repo is currently quite opinionated towards the way I use NixOS, but if you can submit a PR re-enabling channels and adding instructions to the README describing how to set up a regular channel + `configuration.nix` based system I would probably take it.
> # Explanation of why I use flakes
> Now onto explaining flakes. In the Nix world you basically have two ways of using a NixOS configuration. The original channel + `configuration.nix` method is something I would consider outdated. The issue is that channels are impure inputs to your configuration. If you want to copy your configuration to another machine, that other machine will have different versions of the channels, and so you will get different versions of packages, and in an unlucky scenario your configuration could even fail to evaluate e.g. if you are using an unstable channel. You also have no record of the previous versions of the channels on the same machine, so e.g. if something goes wrong after a channel update it's not easy to roll back to the exact previous version.
> 
> Flakes are still considered "experimental", but given that a large part of the Nix community uses them, they are _de facto_ stable enough for regular use and no one would dare (hope) making breaking changes to the flake system because so many people depend on it.
> 
> An important feature of flakes is its concept of "inputs", which can basically replace channels. Inputs are pinned in the `flake.lock` file: https://github.com/kuruczgy/x1e-nixos-config/blob/09fd24afeab6dd380a1040c8c465c18c56b5a196/flake.lock
> 
> Now, if you put your flake based config and `flake.lock` into a git repo (doesn't really make sense to use flakes without one), you have:
> 
> 1. A perfectly reproducible config anyone in the world can reproduce. This is the reason I can upload this repo and be confident that it will just work for other people, without version drift or any other breakage.
> 2. A history of each previously used version of each input. Now if a nixpkgs update breaks something, rolling back is trivial.
> 
> Flakes do have other features too, e.g. being able to use other flakes as inputs, but I would recommend mostly just sticking to using flakes as a replacement for channels, and not much else. If you are interested in the design limitations of flakes and why you should be careful with fully embracing all of the other features, I would recommend this article: https://jade.fyi/blog/flakes-arent-real/
> 
> They way I use flakes is that I have a single flake-based NixOS config repository shared by all of my machines. (The `sudo nixos-rebuild switch --flake .` command automatically selects the right configuration based on the hostname.) This is very useful because I can share NixOS modules between them, and it's also very easy to enforce some common rules.
> 
> Hope this helped, if you have any questions feel free to ask.

Many thanks for the detailed reply! I'll definitely give it a try asap. Thank you for making linux on the slim 7x so easy. is the spottiness of s0ix due to the dts? I think we could report this to the linaro guys in that case.

**Comment by kuruczgy** [comment] 2024-09-03 11:43
Yeah there was a bug with with the screen not resuming, but the patch for it is in Johan's rc6 kernel branch, so I just need to update it in this repo. Suspend is still not very good though, it consumes about 4% battery per hour. I don't know how the different suspend states on aarch64 work, but I was told on IRC that it's known that it isn't hitting the deepest power states yet. Some of the linaro people are also on IRC, so I assume they are aware of the issue.

If you are interested I would recommend joining on IRC/Matrix (links here: https://github.com/aarch64-laptops/build#irc), there is a lot of useful info being shared, I would not have been able to get anywhere near this far without the people there helping.

I will close this issue, the conclusion is that non-flake configs are not supported by this repo right now, but PRs are welcome.

**Closed by kuruczgy** 2024-09-03 11:43 UTC
