### ISSUE TITLE
NixOS system using the module from the latest commit fails to build

### ISSUE THREAD

**Issue by powpingdone** [kuruczgy/x1e-nixos-config#35] opened 2024-10-30 21:55 UTC
```nix
error: builder for '/nix/store/99ypxmvgaygvmaybirgwy9hr3wr2ir26-cpupower-6.12.0-rc5.drv' failed with exit code 1;
...
       > applying patch /nix/store/6yf9bg7a0pvm5ld1vrcgm8lmjiaxwpib-drivers?id=2ad84af4cff9121827d3dd35e293478bdb0b58bb
       > patching file drivers/gpu/drm/Kconfig
       > Reversed (or previously applied) patch detected!  Assume -R? [n]
       > Apply anyway? [n]
       > Skipping patch.
       > 1 out of 1 hunk ignored -- saving rejects to file drivers/gpu/drm/Kconfig.rej
       For full logs, run 'nix log /nix/store/99ypxmvgaygvmaybirgwy9hr3wr2ir26-cpupower-6.12.0-rc5.drv'.
error: 1 dependencies of derivation '/nix/store/yd3dl9569q5gm1ky29f462g9pr7karw6-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/579vafswjf5afxdp3gv2vwjfwi07lf18-unit-cpufreq.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2j1zjsm6gbwgcbqsx480qj7c198pc47m-nixos-system-PPD-ARMTOP-24.11.20241025.18536bf.drv' failed to build
```
Seems like the patch doesn't work as the kernel has the patch already.

**Comment by kuruczgy** [comment] 2024-10-30 22:23
Hm...
1. What does `nix eval .#nixosConfigurations.PPD-ARMTOP.config.boot.kernelPackages.kernel.patches` print? Do you have any extra kernel patches from anywhere?
2. What's your nixpkgs version?

**Comment by powpingdone** [comment] 2024-10-30 22:41
1. 
```nix
[ «derivation /nix/store/63k7ply48axsg2mmmzl93sx39d8fackk-raw.drv» «derivation /nix/store/7msn4iv6mxzkqd05h0y6d5vcnxjlz9s3-9829ac9dd0e827cc62242d8ae8b534e31ffd00bd.patch.drv» «derivation /nix/store/6w49yn5bj4fjqi36jnvgk5sy7pawdvl8-raw.drv» «derivation /nix/store/xawf5vvcd4dj3wxn30jac7ihsf5nfc4p-raw.drv» «derivation /nix/store/ssl4r9bxs5dqshjzyvyw39yzjygkyy3b-raw.drv» «derivation /nix/store/4s4nwzxi8hylhkgxsclkdxlp5vjrkj42-drivers?id=2ad84af4cff9121827d3dd35e293478bdb0b58bb.drv» /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/pkgs/os-specific/linux/kernel/randstruct-provide-seed-5.19.patch ]
```
which the derivations have URLs of:
```
https://lore.kernel.org/linux-kernel/20241003230734.653717-1-ojeda@kernel.org/raw
https://github.com/hogliux/linux-yoga-7x/commit/9829ac9dd0e827cc62242d8ae8b534e31ffd00bd.patch
https://lore.kernel.org/linux-devicetree/20240927185345.3680-1-maccraft123mc@gmail.com/raw
https://lore.kernel.org/platform-driver-x86/20240927185345.3680-2-maccraft123mc@gmail.com/raw
https://lore.kernel.org/linux-arm-msm/20240927185345.3680-3-maccraft123mc@gmail.com/raw
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/patch/drivers?id=2ad84af4cff9121827d3dd35e293478bdb0b58bb
```
2.
```
$ nix-shell -p nix-info --run "nix-info -m"            
 - system: `"aarch64-linux"`
 - host os: `Linux 6.12.0-rc4, NixOS, 24.11 (Vicuna), 24.11.20241025.18536bf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source`
 ```
```

**Comment by kuruczgy** [comment] 2024-10-31 00:19
You need to look into where `https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/patch/drivers?id=2ad84af4cff9121827d3dd35e293478bdb0b58bb` is coming from, because it isn't from this repo.

**Comment by powpingdone** [comment] 2024-10-31 00:57
Ah yup. It was a rouge patch.

**Comment by kuruczgy** [comment] 2024-10-31 01:13
Sounds like the issue is resolved then, closing :) (But if you encounter any further problems feel free to open another issue of course.)

**Closed by kuruczgy** 2024-10-31 01:13 UTC
